[project]
name = "tasklist"
version = "0.1.0"

requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]",
    "sqlalchemy",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

